[api]
    username = "admin"
    token = "admin"
    address = "http://localhost:8080"

[cache]
    enabled = true
    concurrency = 4
    max_size = 1000
    expire_time = 6
    expire_time-unit = "HOURS"
